project:
  type: website

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Zephaniahc
      - icon: linkedin
        href: https://linkedin.com/zephaniah-chekelea/
      
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

